[versions]
agp = "8.2.0" # Ganti dengan versi plugin Android Gradle Anda jika berbeda
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
extJunit = "1.1.5"
espressoCore = "3.5.1"
camerax = "1.3.3"
generativeai = "0.7.0"
desugar = "2.0.4"
# =======================================
# PERUBAHAN: TAMBAHKAN VERSI GUAVA
# =======================================
guava = "33.2.1-android"


[libraries]
android-application = { group = "com.android.application", name = "gradle", version.ref = "agp" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Library CameraX
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }

# Library Gemini
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
# =======================================
# PERUBAHAN: TAMBAHKAN GUAVA (ListenableFuture)
# =======================================
guava-android = { group = "com.google.guava", name = "guava", version.ref = "guava" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[bundles]

